### ISSUE TITLE
problem about backbone_resnet.params

### ISSUE THREAD

**Issue by ineslyl** [cvcode18/imbalanced_learning#11]
Hello, I've download resnet101_v1-d988c13d.zip and made this param as " backbone_resnet.params". When i run "python main.py --data_path=/path/data", i got this problem :
[11:09:00] src/io/./image_iter_common.h:77: Loaded ImageList from wider_records/training_list.lst 22958 Image records
[11:09:00] src/io/iter_image_recordio_2.cc:172: ImageRecordIOParser2: wider_records/training_list.rec, use 4 threads for decoding..
[11:09:01] src/io/./image_iter_common.h:77: Loaded ImageList from wider_records/valid_list.lst 5382 Image records
[11:09:01] src/io/iter_image_recordio_2.cc:172: ImageRecordIOParser2: wider_records/valid_list.rec, use 4 threads for decoding..
[11:09:01] src/io/./image_iter_common.h:77: Loaded ImageList from wider_records/testing_list.lst 29177 Image records
[11:09:01] src/io/iter_image_recordio_2.cc:172: ImageRecordIOParser2: wider_records/testing_list.rec, use 4 threads for decoding..
/usr/local/python3/lib/python3.5/site-packages/mxnet/gluon/block.py:420: UserWarning: load_params is deprecated. Please use load_parameters.
  warnings.warn("load_params is deprecated. Please use load_parameters.")
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    train(args, ctx)
  File "/home/imbalanced_learning/wider_training.py", line 97, in train
    model.load_params('saved_models/backbone_resnet.params', ctx=ctx)
  File "/usr/local/python3/lib/python3.5/site-packages/mxnet/gluon/block.py", line 421, in load_params
    self.load_parameters(filename, ctx, allow_missing, ignore_extra)
  File "/usr/local/python3/lib/python3.5/site-packages/mxnet/gluon/block.py", line 394, in load_parameters
    name, filename, _brief_print_list(loaded.keys()))
AssertionError: Parameter 'stage3_conv31_bias' is missing in file 'saved_models/backbone_resnet.params', which contains parameters: 'features.6.18.body.0.weight', 'features.6.20.body.1.running_mean', 'features.6.17.body.7.running_mean', ..., 'features.6.19.body.7.gamma', 'features.6.22.body.3.weight', 'features.6.20.body.1.beta', 'features.6.5.body.1.running_mean'. Set allow_missing=True to ignore missing parameters.

Then, i set allow_missing=True and ignore_extra=True. when i run this again, it shows that "mxnet.base.MXNetError: [11:10:00] src/io/local_filesys.cc:199: Check failed: allow_null  LocalFileSystem::Open "saved_models/fsr_stage_2.params": No such file or directory"

Anyone met this problem before, Is the problem with "backbone_resnet.params" ? 

ps: Centos7 + Python 3.5 + mxnet-cu90

**Comment by wwwrrrcom** [comment]
I have encountered the same problem. Has your problem been solved?

**Comment by ideaflow** [comment]
@ineslyl I met this problem too, and I'm not sure if it's ok to rename the "resnet101_v1-d988c13d.params" to "backbone_resnet.params", maybe it's not the params file we need, did you solved this problem?

**Comment by cute-walk** [comment]
Did anyone sloved this problem?

**Comment by cute-walk** [comment]
I also encountered the same problem.

```
[12:39:49] src/io/./image_iter_common.h:77: Loaded ImageList from wider_records/training_list.lst 22958 Image records
[12:39:49] src/io/iter_image_recordio_2.cc:172: ImageRecordIOParser2: wider_records/training_list.rec, use 4 threads for decoding..
[12:39:49] src/io/./image_iter_common.h:77: Loaded ImageList from wider_records/valid_list.lst 5382 Image records
[12:39:49] src/io/iter_image_recordio_2.cc:172: ImageRecordIOParser2: wider_records/valid_list.rec, use 4 threads for decoding..
[12:39:49] src/io/./image_iter_common.h:77: Loaded ImageList from wider_records/testing_list.lst 29177 Image records
[12:39:49] src/io/iter_image_recordio_2.cc:172: ImageRecordIOParser2: wider_records/testing_list.rec, use 4 threads for decoding..
/nfs30/ckj/anaconda3/envs/DIAA_ECCV_2018/lib/python3.5/site-packages/mxnet/gluon/block.py:1159: UserWarning: Cannot decide type for the following arguments. Consider providing them as input:
	data: None
  input_sym_arg_type = in_param.infer_type()[0]
/nfs30/ckj/anaconda3/envs/DIAA_ECCV_2018/lib/python3.5/site-packages/mxnet/gluon/block.py:428: UserWarning: load_params is deprecated. Please use load_parameters.
  warnings.warn("load_params is deprecated. Please use load_parameters.")
Traceback (most recent call last):
  File "/nfs30/ckj/PycharmProjects/imbalanced_learning-master_new/main.py", line 32, in <module>
    train(args, ctx)
  File "/nfs30/ckj/PycharmProjects/imbalanced_learning-master_new/wider_training.py", line 97, in train
    model.load_params('saved_models/backbone_resnet.params', ctx=ctx)
  File "/nfs30/ckj/anaconda3/envs/DIAA_ECCV_2018/lib/python3.5/site-packages/mxnet/gluon/block.py", line 429, in load_params
    self.load_parameters(filename, ctx, allow_missing, ignore_extra)
  File "/nfs30/ckj/anaconda3/envs/DIAA_ECCV_2018/lib/python3.5/site-packages/mxnet/gluon/block.py", line 402, in load_parameters
    name, filename, _brief_print_list(loaded.keys()))
AssertionError: Parameter 'stage3_batchnorm1_gamma' is missing in file 'saved_models/backbone_resnet.params', which contains parameters: 'features.6.1.body.6.weight', 'features.4.0.body.7.running_mean', 'features.6.14.body.1.beta', ..., 'features.6.1.body.0.bias', 'output.bias', 'features.6.17.body.6.weight', 'features.6.7.body.0.weight'. Set allow_missing=True to ignore missing parameters.
```

Did anyone sloved this problem?

**Comment by cute-walk** [comment]
> Hello, I've download resnet101_v1-d988c13d.zip and made this param as " backbone_resnet.params". When i run "python main.py --data_path=/path/data", i got this problem :
> [11:09:00] src/io/./image_iter_common.h:77: Loaded ImageList from wider_records/training_list.lst 22958 Image records
> [11:09:00] src/io/iter_image_recordio_2.cc:172: ImageRecordIOParser2: wider_records/training_list.rec, use 4 threads for decoding..
> [11:09:01] src/io/./image_iter_common.h:77: Loaded ImageList from wider_records/valid_list.lst 5382 Image records
> [11:09:01] src/io/iter_image_recordio_2.cc:172: ImageRecordIOParser2: wider_records/valid_list.rec, use 4 threads for decoding..
> [11:09:01] src/io/./image_iter_common.h:77: Loaded ImageList from wider_records/testing_list.lst 29177 Image records
> [11:09:01] src/io/iter_image_recordio_2.cc:172: ImageRecordIOParser2: wider_records/testing_list.rec, use 4 threads for decoding..
> /usr/local/python3/lib/python3.5/site-packages/mxnet/gluon/block.py:420: UserWarning: load_params is deprecated. Please use load_parameters.
> warnings.warn("load_params is deprecated. Please use load_parameters.")
> Traceback (most recent call last):
> File "main.py", line 32, in
> train(args, ctx)
> File "/home/imbalanced_learning/wider_training.py", line 97, in train
> model.load_params('saved_models/backbone_resnet.params', ctx=ctx)
> File "/usr/local/python3/lib/python3.5/site-packages/mxnet/gluon/block.py", line 421, in load_params
> self.load_parameters(filename, ctx, allow_missing, ignore_extra)
> File "/usr/local/python3/lib/python3.5/site-packages/mxnet/gluon/block.py", line 394, in load_parameters
> name, filename, _brief_print_list(loaded.keys()))
> AssertionError: Parameter 'stage3_conv31_bias' is missing in file 'saved_models/backbone_resnet.params', which contains parameters: 'features.6.18.body.0.weight', 'features.6.20.body.1.running_mean', 'features.6.17.body.7.running_mean', ..., 'features.6.19.body.7.gamma', 'features.6.22.body.3.weight', 'features.6.20.body.1.beta', 'features.6.5.body.1.running_mean'. Set allow_missing=True to ignore missing parameters.
> 
> Then, i set allow_missing=True and ignore_extra=True. when i run this again, it shows that "mxnet.base.MXNetError: [11:10:00] src/io/local_filesys.cc:199: Check failed: allow_null LocalFileSystem::Open "saved_models/fsr_stage_2.params": No such file or directory"
> 
> Anyone met this problem before, Is the problem with "backbone_resnet.params" ?
> 
> ps: Centos7 + Python 3.5 + mxnet-cu90


When the program "python main.py --data_path=/path/data" is run to start the program, what does ‘data_path' mean?
 I have not found any variables related to "args.data_path" elsewhere in the program.
